import Link from "next/link";
import { ArrowRight, BookMarked, CheckCircle2, Clock3, Compass, Layers3, PlayCircle } from "lucide-react";
import { PageHero, Pill, Progress, SectionHead } from "@/components/ui";
import { courses, curriculum } from "@/lib/data";

const groups = ["AI 基础","Prompt 与 Context","AI 搜索与 Research","AI 学习","AI 办公","AI 内容创作","AI 图片","AI 视频","AI Coding","Workflow","Agent","AI 原理"];
export default function LearnPage(){return <>
  <PageHero eyebrow="学习中心" title="学会与 AI 一起完成任务" intro="课程不按工具按钮组织，而是围绕任务定义、背景提供、结果查证和工作流构建。你可以系统学习，也可以从今天的问题开始。"><div className="button-row"><Link className="button primary" href="/learn/context-design"><PlayCircle size={17}/> 继续上次课程</Link><Link className="button" href="/assessment"><Compass size={17}/> 生成我的学习路径</Link></div></PageHero>
  <nav className="subnav">{groups.map((g,i)=><a href={`#g${i}`} className={i===0?"active":""} key={g}>{g}</a>)}</nav>
  <section className="section white"><div className="container"><SectionHead eyebrow="四个阶段" title="能力成长路线"/><div className="learning-map">{curriculum.map((c,i)=><div className="map-step" style={{background:c.color}} key={c.title}><i>0{i+1}</i><small>{c.group} · {c.count} 节课</small><b>{c.title}</b><p>{c.desc}</p><span>{i===0?"建议从这里开始":"完成上一阶段后解锁建议"}</span></div>)}</div></div></section>
  <section className="section"><div className="container"><div className="learn-layout"><aside className="learn-sidebar"><b>课程目录</b>{groups.map((g,i)=><a href={`#g${i}`} key={g}><span>0{i+1}</span>{g}</a>)}</aside><div className="learn-main"><SectionHead title="为你推荐" action="调整目标" href="/assessment"/><div className="resume-card"><div><Pill tone="green">正在学习</Pill><h2>从 Prompt 到任务设计</h2><p>你已经掌握了“目标”和“受众”，下一节学习如何给出足够的 Context。</p><Progress value={62}/><small>7 / 11 小节 · 预计还需 18 分钟</small></div><Link className="button primary" href="/learn/context-design">继续学习 <ArrowRight size={16}/></Link></div><div className="lesson-cards">{courses.concat(courses.slice(0,2)).map((c,i)=><Link id={`g${i}`} className="lesson-card" href="/learn/context-design" key={`${c.title}${i}`}><span className={`lesson-art art-${i%4}`}><PlayCircle/></span><div><div className="lesson-top"><Pill tone={i%3===0?"orange":"blue"}>{c.level}</Pill><span><Clock3 size={12}/> {22+i*4} 分钟</span></div><h3>{c.title}</h3><p>{["用一张地图分清模型、产品、API 和 Agent。","学会让 AI 在正确的背景中完成明确任务。","用来源、交叉验证与常识检查降低幻觉。","把输入、处理、判断和输出连接成可复用流程。"][i%4]}</p><div className="lesson-foot"><span><BookMarked size={13}/> {5+i} 个知识块</span>{c.progress>0&&<span><CheckCircle2 size={13}/> 已学习 {c.progress}%</span>}</div></div></Link>)}</div></div></div></div></section>
  </>}
