"use client";
import { useMemo, useState } from "react";
import { Atom, BrainCircuit, Braces, Check, CircleDotDashed, GitBranch, Network, Play, RotateCcw, ScanSearch, Sparkles } from "lucide-react";
import { PageHero, Pill, SectionHead } from "@/components/ui";

const labs=["Prompt Builder","Token 可视化","Context 窗口","幻觉挑战","搜索 vs AI","Embedding 地图","Attention 观察","Workflow 构建器","Agent 模拟器","工具选择游戏"];
export default function LabPage(){const [fields,setFields]=useState({goal:"写一封项目延期邮件",context:"原定周五交付，接口变更导致延期",audience:"合作三年的重要客户",constraints:"坦诚，不甩锅，180 字以内",format:"主题 + 正文"});const [generated,setGenerated]=useState(false);const output=useMemo(()=>`你是一名重视长期关系的项目负责人。\n\n任务：${fields.goal}\n背景：${fields.context}\n读者：${fields.audience}\n要求：${fields.constraints}\n输出：${fields.format}`, [fields]);return <>
  <PageHero eyebrow="AI 实验室" title="把抽象概念变成可以玩的东西" intro="不用先背术语。动手改变输入、观察结果、建立直觉，再回到原理。所有实验都在浏览器中运行，不会上传你的内容。"/>
  <section className="lab-app"><aside className="lab-menu"><b>实验目录</b>{labs.map((x,i)=><button className={i===0?"active":""} key={x}>{[<Braces/>,<CircleDotDashed/>,<Atom/>,<ScanSearch/>,<BrainCircuit/>,<Network/>,<CircleDotDashed/>,<GitBranch/>,<Sparkles/>,<Check/>][i]}<span>{x}</span>{i<3&&<small>推荐</small>}</button>)}</aside><div className="lab-workspace"><div className="lab-heading"><div><Pill tone="blue">实验 01</Pill><h1>Prompt Builder</h1><p>把一个模糊要求，逐步变成 AI 能可靠执行的任务。</p></div><button className="button" onClick={()=>{setGenerated(false);setFields({goal:"",context:"",audience:"",constraints:"",format:""})}}><RotateCcw size={15}/> 重置</button></div><div className="builder-grid"><div className="builder-form">{Object.entries({goal:"你要完成什么？",context:"正在发生什么？",audience:"谁会使用结果？",constraints:"必须做到 / 避免什么？",format:"希望怎样交付？"}).map(([key,label],i)=><label key={key}><span><i>{i+1}</i>{label}</span><textarea value={fields[key as keyof typeof fields]} onChange={e=>setFields({...fields,[key]:e.target.value})}/></label>)}<button className="button blue" onClick={()=>setGenerated(true)}><Sparkles size={16}/> 生成结构化任务</button></div><div className="builder-output"><span>结构预览</span><h3>你的任务说明</h3><pre>{output}</pre><div className="quality-list"><b>质量检查</b>{[["目标明确",!!fields.goal],["背景充分",fields.context.length>8],["受众清楚",!!fields.audience],["边界具体",fields.constraints.length>8],["格式可执行",!!fields.format]].map(([x,ok])=><div key={String(x)} className={ok?"ok":""}><span>{ok?<Check/>:"·"}</span>{x}</div>)}</div>{generated&&<div className="generated-note"><Check/> 已生成。现在你可以复制它，或进入“结果迭代”实验继续优化。</div>}</div></div></div></section>
  <section className="section"><div className="container"><SectionHead eyebrow="接下来" title="继续探索实验"/><div className="lab-card-grid">{labs.slice(1).map((x,i)=><div className="lab-card" key={x}><span>0{i+2}</span><h3>{x}</h3><p>{["看看一句中文如何被拆成模型处理的片段。","把资料放进有限窗口，观察哪些信息会被挤出。","识别看似可信、实际没有来源支持的说法。"][i%3]}</p><button>进入实验 →</button></div>)}</div></div></section>
  </>}
